FROM php:8.0-apache AS builder
RUN apt update && apt install -y git
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
COPY ./api/composer.json /var/www/html
COPY ./api/composer.lock /var/www/html
RUN composer install --no-dev
COPY ./api /var/www/html

FROM php:8.0-apache
COPY --from=builder /var/www/html /var/www/html
RUN a2enmod rewrite
RUN a2enmod actions
COPY ./docker/php/apache2.conf /etc/apache2/
RUN service apache2 restart

WORKDIR /var/www/html

EXPOSE 80
