kind: pipeline
name: default

steps:
- name: install
  image: composer
  commands:
  - cd api/
  - composer install

- name: lint
  image: php:8
  commands:
  - cd api/
  - vendor/bin/phpcs --standard=PSR12 config/
  - vendor/bin/phpcs --standard=PSR12 public/
  - vendor/bin/phpcs --standard=PSR12 src/
  - vendor/bin/phpcs --standard=PSR12 templates/
  - vendor/bin/phpcs --standard=PSR12 tests/

- name: test
  image: php:8
  commands:
  - cd api/
  - vendor/bin/phpunit
