kind: pipeline
name: default

steps:
- name: install
  image: composer
  commands:
  - cd api/
  - composer install

- name: lint
  image: php:8
  commands:
  - cd api/
  - vendor/bin/phpcs --standard=ruleset.xml src/

- name: test
  image: php:8
  commands:
  - cd api/
  - vendor/bin/phpunit
