version: '3.9'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile.dev
      args:
        PHP_VERSION: ${PHP_VERSION}
    container_name: slim-app
    env_file:
      - .env
    volumes:
      - ./api:/var/www/html
    ports:
      - '8080:80'
    networks:
      - magnet-2-torrent

  composer:
    image: composer:latest
    container_name: slim-composer
    volumes:
      - ./api:/var/www/html
    working_dir: /var/www/html
    networks:
      - magnet-2-torrent

  phpunit:
    image: php:8.0-cli-alpine3.12
    container_name: slim-phpunit
    volumes:
      - ./api:/var/www/html
    working_dir: /var/www/html
    entrypoint: 'vendor/bin/phpunit'
    networks:
      - magnet-2-torrent

networks:
  magnet-2-torrent:
